[package]
name = "boao"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-where = "1.5.0"
paste = "1.0.15"
rustc-hash = "2.1.1"
scopeguard = "1.2.0"
thiserror = "2.0.12"

[dependencies.bytemuck]
version = "1.23.1"
default-features = false
features = ["derive"]
