[package]
name = "arid"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-where = "1.3.0"
hashbrown = "0.15.2"
index_vec = "0.1.4"
late-struct = "0.1.0"
paste = "1.0.15"
rustc-hash = "2.1.1"
scopeguard = "1.2.0"
thunderdome = "0.6.1"
