[package]
name = "late-struct"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.1"
scopeguard = "1.2.0"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
linkme = "0.3.32"

[target.'cfg(target_family = "wasm")'.dependencies]
inventory = "0.3.20"
